name: Test and build
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Install apt dependencies
        run: sudo apt update && sudo apt-get install afflib-tools archivemount avfs cryptsetup disktype exfat-fuse exfat-utils libguestfs-tools libvshadow-utils lvm2 mdadm mtd-utils ocfs2-tools open-vm-tools qemu-utils sleuthkit sqlite3 squashfs-tools vmfs-tools xfsprogs xmount zlib1g-dev
      - name: pip install
        run: sudo pip install -r requirements.txt && sudo pip install -e .
      - name: Download test images
        run: sudo python download-test-images.py --dftt
        working-directory: tests/
      - name: Run tests
        run: sudo pytest
        working-directory: tests/
  build:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Build wheel
        run: sudo pip install wheel && sudo python setup.py sdist bdist_wheel

