name: Thumbtack workflow
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Install apt dependencies
        run: sudo apt update && sudo apt-get install afflib-tools archivemount avfs cryptsetup disktype exfat-fuse exfat-utils libguestfs-tools libvshadow-utils lvm2 mdadm mtd-utils ocfs2-tools open-vm-tools qemu-utils sleuthkit sqlite3 squashfs-tools vmfs-tools xfsprogs xmount zlib1g-dev
      - name: pip install
        run: sudo pip install -r requirements.txt && sudo pip install -e .
      - name: Download test images
        run: sudo python download-test-images.py --dftt
        working-directory: tests/
      - name: Run tests
        run: sudo pytest
        working-directory: tests/
  build:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Build wheel
        run: sudo pip install wheel && sudo python setup.py sdist bdist_wheel
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Build wheel
        run: sudo pip install wheel && sudo python setup.py sdist bdist_wheel
      - name: Push to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
  docker-image:
    needs: deploy
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/mitre/thumbtack
          tags: type=ref,event=tag

      - name: Build and push Docker image
        if: startsWith(github.ref, 'refs/tags')
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./docker/thumbtack/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
